"""
agents/packaging/sbom_generator.py

Phase 4 — Software Bill of Materials (SBOM) Generator.

Generates a SPDX-JSON SBOM for every OCI image using Anchore Syft.
The SBOM is:
  1. Generated by a Kubernetes Job (in-cluster) or subprocess (local dev)
  2. Uploaded to R2 at:  s3://<bucket>/security/sbom/<model>-<version>-sbom.spdx.json
  3. Attached to the OCI image as a Cosign OCI attestation (handled by CosignSigner)
  4. Persisted as a row in sbom_records with the R2 URI and package count

SBOM format: SPDX 2.3 JSON (--output spdx-json via Syft)

SPDX JSON structure (subset):
  {
    "spdxVersion": "SPDX-2.3",
    "name": "<image>",
    "packages": [
      {
        "SPDXID": "SPDXRef-...",
        "name": "cryptography",
        "versionInfo": "42.0.5",
        "supplier": "Organization: PyPI",
        "filesAnalyzed": false
      }
    ]
  }

The package_count field in sbom_records reflects the total number of
inventoried packages — useful for quick security posture assessment.
"""
from __future__ import annotations

import json
import logging
import subprocess
import time
import uuid
from dataclasses import dataclass
from typing import Any, Optional

from configs.settings import settings

logger = logging.getLogger(__name__)

_SYFT_IMAGE          = "anchore/syft:latest"
_POLL_INTERVAL_SECS  = 8
_SBOM_TIMEOUT_SECS   = 600


# ── Result model ──────────────────────────────────────────────────────────────

@dataclass
class SBOMRecord:
    """Metadata for one generated SBOM."""
    image_digest:  str
    model_name:    str
    model_version: str
    format:        str            # "spdx-json"
    r2_uri:        str            # s3://bucket/security/sbom/...
    package_count: int
    syft_version:  Optional[str]
    raw_sbom:      dict[str, Any] # full parsed SPDX JSON (for attestation upload)


# ── Generator ─────────────────────────────────────────────────────────────────

class SBOMGenerator:
    """
    Generates and stores an SPDX-JSON SBOM for a given OCI image.

    Args:
        model_name:    MLflow registered model name.
        model_version: MLflow model version string.
        pool:          asyncpg pool for sbom_records persistence.
    """

    def __init__(
        self,
        model_name:    str,
        model_version: str,
        pool:          Any,
    ) -> None:
        self._model_name    = model_name
        self._model_version = model_version
        self._pool          = pool
        self._s3            = self._make_s3_client()

    async def generate(
        self,
        image_uri:    str,
        image_digest: str,
        workflow_id:  Optional[str] = None,
    ) -> SBOMRecord:
        """
        Generate an SPDX-JSON SBOM for the image and upload it to R2.

        Args:
            image_uri:    Full digest-pinned image reference.
            image_digest: sha256 digest string.
            workflow_id:  Optional FK to workflows table.

        Returns:
            SBOMRecord with R2 URI, package count, and raw SBOM data.

        Raises:
            RuntimeError: if Syft cannot scan the image or the upload fails.
        """
        logger.info("SBOM generation starting for image=%s", image_uri)

        if settings.k8s_in_cluster:
            raw_sbom = await self._generate_via_k8s_job(image_uri)
        else:
            raw_sbom = self._generate_via_subprocess(image_uri)

        package_count = self._count_packages(raw_sbom)
        syft_version  = self._extract_syft_version(raw_sbom)
        r2_uri        = await self._upload_sbom(image_digest, raw_sbom)

        record = SBOMRecord(
            image_digest=  image_digest,
            model_name=    self._model_name,
            model_version= self._model_version,
            format=        "spdx-json",
            r2_uri=        r2_uri,
            package_count= package_count,
            syft_version=  syft_version,
            raw_sbom=      raw_sbom,
        )

        await self._persist(record, workflow_id)

        logger.info(
            "SBOM complete: packages=%d r2=%s", package_count, r2_uri
        )
        return record

    # ── K8s Job path ──────────────────────────────────────────────────────────

    async def _generate_via_k8s_job(self, image_uri: str) -> dict[str, Any]:
        """Create a Syft Job, wait for completion, parse SPDX JSON from logs."""
        job_name = f"syft-sbom-{uuid.uuid4().hex[:8]}"
        manifest = self._build_syft_job_manifest(job_name, image_uri)

        k8s_batch = self._k8s_batch_api()
        k8s_batch.create_namespaced_job(
            namespace=settings.k8s_namespace,
            body=manifest,
        )
        logger.info("Syft Job created: %s", job_name)

        return await self._wait_for_syft_job(job_name, k8s_batch)

    def _build_syft_job_manifest(
        self, job_name: str, image_uri: str
    ) -> dict[str, Any]:
        """Build the K8s BatchV1 Job manifest for Syft."""
        return {
            "apiVersion": "batch/v1",
            "kind":       "Job",
            "metadata": {
                "name":      job_name,
                "namespace": settings.k8s_namespace,
                "labels": {
                    "mlops.component":     "syft-sbom",
                    "mlops.model_name":    self._model_name,
                    "mlops.model_version": self._model_version,
                },
            },
            "spec": {
                "ttlSecondsAfterFinished": 300,
                "backoffLimit": 1,
                "template": {
                    "spec": {
                        "restartPolicy": "OnFailure",
                        "containers": [{
                            "name":  "syft",
                            "image": _SYFT_IMAGE,
                            "args":  [image_uri, "-o", "spdx-json", "--quiet"],
                            "env": [
                                {
                                    "name": "SYFT_REGISTRY_AUTH_USERNAME",
                                    "valueFrom": {"secretKeyRef": {
                                        "name": "dockerhub-credentials",
                                        "key":  "username",
                                    }},
                                },
                                {
                                    "name": "SYFT_REGISTRY_AUTH_PASSWORD",
                                    "valueFrom": {"secretKeyRef": {
                                        "name": "dockerhub-credentials",
                                        "key":  "password",
                                    }},
                                },
                            ],
                            "resources": {
                                "requests": {"memory": "256Mi", "cpu": "250m"},
                                "limits":   {"memory": "512Mi", "cpu": "500m"},
                            },
                        }],
                    }
                },
            },
        }

    async def _wait_for_syft_job(
        self, job_name: str, k8s_batch: Any
    ) -> dict[str, Any]:
        """Poll the Syft Job until done, then fetch and parse its stdout."""
        k8s_core   = self._k8s_core_api()
        start_time = time.monotonic()

        while True:
            if time.monotonic() - start_time > _SBOM_TIMEOUT_SECS:
                raise RuntimeError(
                    f"Syft Job {job_name!r} timed out after {_SBOM_TIMEOUT_SECS}s"
                )
            job = k8s_batch.read_namespaced_job(
                name=job_name, namespace=settings.k8s_namespace
            )
            if job.status.succeeded:
                break
            if job.status.failed:
                logs = self._fetch_pod_log(k8s_core, job_name)
                raise RuntimeError(
                    f"Syft Job {job_name!r} failed.\nOutput:\n"
                    + "\n".join(logs.splitlines()[-20:])
                )
            time.sleep(_POLL_INTERVAL_SECS)

        log_text = self._fetch_pod_log(k8s_core, job_name)
        return self._parse_spdx_json(log_text)

    def _fetch_pod_log(self, k8s_core: Any, job_name: str) -> str:
        pods = k8s_core.list_namespaced_pod(
            namespace=settings.k8s_namespace,
            label_selector=f"job-name={job_name}",
        )
        if not pods.items:
            raise RuntimeError(f"No pods found for Syft Job {job_name!r}")
        pod_name = pods.items[0].metadata.name
        return k8s_core.read_namespaced_pod_log(
            name=pod_name,
            namespace=settings.k8s_namespace,
            container="syft",
        )

    # ── Subprocess path ───────────────────────────────────────────────────────

    def _generate_via_subprocess(self, image_uri: str) -> dict[str, Any]:
        """Run `syft image -o spdx-json` locally (dev mode only)."""
        logger.info("Running Syft locally (dev mode) against %s", image_uri)
        cmd = ["syft", image_uri, "-o", "spdx-json", "--quiet"]
        try:
            proc = subprocess.run(
                cmd,
                capture_output=True,
                text=True,
                timeout=_SBOM_TIMEOUT_SECS,
                check=True,
            )
        except FileNotFoundError as exc:
            raise RuntimeError(
                "Syft binary not found on PATH. "
                "Install syft or set k8s_in_cluster=true."
            ) from exc
        except subprocess.CalledProcessError as exc:
            raise RuntimeError(
                f"Syft exited {exc.returncode}. stderr:\n{exc.stderr[:500]}"
            ) from exc
        except subprocess.TimeoutExpired as exc:
            raise RuntimeError(
                f"Syft subprocess timed out scanning {image_uri!r}"
            ) from exc

        return self._parse_spdx_json(proc.stdout)

    # ── SPDX parsing ──────────────────────────────────────────────────────────

    @staticmethod
    def _parse_spdx_json(raw_text: str) -> dict[str, Any]:
        """Parse SPDX JSON output from Syft stdout."""
        start = raw_text.find("{")
        if start == -1:
            raise RuntimeError(
                f"Syft output contains no JSON object. "
                f"First 300 chars: {raw_text[:300]!r}"
            )
        try:
            return json.loads(raw_text[start:])
        except json.JSONDecodeError as exc:
            raise RuntimeError(
                f"Failed to parse Syft SPDX JSON: {exc}. "
                f"Snippet: {raw_text[start:start+200]!r}"
            ) from exc

    @staticmethod
    def _count_packages(sbom: dict[str, Any]) -> int:
        """Count inventoried packages from the SPDX packages array."""
        packages = sbom.get("packages") or []
        # Exclude the root "describes" package (the image itself)
        return sum(
            1 for p in packages
            if not p.get("SPDXID", "").endswith("DOCUMENT")
            and p.get("name") != sbom.get("name")
        )

    @staticmethod
    def _extract_syft_version(sbom: dict[str, Any]) -> Optional[str]:
        """Extract Syft version from SPDX creationInfo."""
        creation_info = sbom.get("creationInfo", {})
        for creator in creation_info.get("creators", []):
            if creator.startswith("Tool: syft-"):
                return creator.split("syft-", 1)[-1]
        return None

    # ── R2 upload ─────────────────────────────────────────────────────────────

    async def _upload_sbom(
        self, image_digest: str, raw_sbom: dict[str, Any]
    ) -> str:
        """Upload SPDX JSON to R2. Returns the s3:// URI."""
        # Use digest suffix (last 12 chars) to distinguish multiple versions
        digest_suffix = image_digest.replace("sha256:", "")[:12]
        key = (
            f"{settings.r2_sbom_prefix}/"
            f"{self._model_name}-v{self._model_version}-{digest_suffix}-sbom.spdx.json"
        )
        sbom_bytes = json.dumps(raw_sbom, indent=2).encode("utf-8")
        try:
            self._s3.put_object(
                Bucket=settings.r2_bucket_name,
                Key=key,
                Body=sbom_bytes,
                ContentType="application/json",
            )
        except Exception as exc:
            raise RuntimeError(
                f"Failed to upload SBOM to R2 at key {key!r}: {exc}"
            ) from exc

        return f"s3://{settings.r2_bucket_name}/{key}"

    # ── Persistence ────────────────────────────────────────────────────────────

    async def _persist(
        self, record: SBOMRecord, workflow_id: Optional[str]
    ) -> None:
        """INSERT into sbom_records."""
        async with self._pool.acquire() as conn:
            await conn.execute(
                """
                INSERT INTO sbom_records
                    (image_digest, model_name, model_version, format,
                     r2_uri, package_count, syft_version, workflow_id)
                VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
                """,
                record.image_digest,
                record.model_name,
                record.model_version,
                record.format,
                record.r2_uri,
                record.package_count,
                record.syft_version,
                workflow_id,
            )

    # ── Client factories ───────────────────────────────────────────────────────

    @staticmethod
    def _make_s3_client() -> Any:
        import boto3
        return boto3.client(
            "s3",
            endpoint_url=     settings.r2_endpoint_url,
            aws_access_key_id=settings.r2_access_key_id,
            aws_secret_access_key=settings.r2_secret_access_key,
            region_name=settings.r2_region,
        )

    @staticmethod
    def _k8s_batch_api() -> Any:
        from kubernetes import client as k8s_client, config as k8s_config
        try:
            if settings.k8s_in_cluster:
                k8s_config.load_incluster_config()
            else:
                k8s_config.load_kube_config()
        except Exception:
            pass
        return k8s_client.BatchV1Api()

    @staticmethod
    def _k8s_core_api() -> Any:
        from kubernetes import client as k8s_client
        return k8s_client.CoreV1Api()