"""
feast/feature_views.py
───────────────────────
V2 Feast feature definitions.

What changed from V1:
  V1: FileSource pointing to a local synthetic parquet generated by
      generate_sample_features() — no real data, no R2 integration.
  V2:
    - Offline store: R2-backed Parquet files written by DataAgent per workflow.
      The FileSource path is resolved at materialize time from the workflow-
      specific parquet written by DataAgent._materialize_features().
    - Online store: Redis (same connection string as settings.feast_redis_connection_string)
    - Feature views are registered here statically; DataAgent adds dynamic
      per-dataset views via register_dynamic_feature_view() below.
    - entity key: record_id (Int64) — stable join key written by DataAgent.
    - TTLs: 1-day for high-churn numeric features, 7-day for entity metadata.

Apply with:
    feast apply

Materialize (called by DataAgent._materialize_features, not manually):
    feast materialize-incremental $(date -u +"%Y-%m-%dT%H:%M:%S")

Verify online store (Redis health check):
    feast feature-store status
"""
from __future__ import annotations

import logging
from datetime import timedelta
from pathlib import Path
from typing import Optional

import pandas as pd
from feast import (
    Entity,
    FeatureStore,
    FeatureView,
    Field,
    FileSource,
    PushSource,
    RequestSource,
)
from feast.types import Float32, Float64, Int64, String, Bool

logger = logging.getLogger(__name__)

# Entity definition:
# record_id is the universal join key. DataAgent writes it as a sequential
# integer, but it can be any stable identifier (UUID, customer_id, etc.).
record = Entity(
    name="record",
    join_keys=["record_id"],
    description="Universal record identifier written by DataAgent per ingested row.",
    tags={"team": "mlops", "owner": "data-agent"},
)

# Offline source: DataAgent writes per-workflow Parquet here:
# In production: DataAgent writes to /feast/data/features_{workflow_id}.parquet
# feast apply merges all parquets in this directory as a unified offline source.
_OFFLINE_DATA_DIR = Path(__file__).parent / "data"
_OFFLINE_DATA_DIR.mkdir(parents=True, exist_ok=True)

# Wildcard FileSource — Feast merges all parquets in the directory at
# get_historical_features() time. DataAgent writes {features_<workflow_id>.parquet}.
numeric_source = FileSource(
    path=str(_OFFLINE_DATA_DIR / "features_dev_fixture.parquet"), # This path is now set up for local-dev env it will be changed once the Docker has been enabled
    timestamp_field="event_timestamp",
    description="Numeric features materialized from each ingestion workflow.",
)

metadata_source = FileSource(
    path=str(_OFFLINE_DATA_DIR / "features_dev_fixture.parquet"),
    timestamp_field="event_timestamp",
    description="Entity-level metadata columns co-located with numeric features.",
)

# Feature views
# Numeric features — generic schema covering the baseline synthetic + real columns.
# Real projects extend this by calling register_dynamic_feature_view() after
# the first ingestion so the schema reflects actual column names.
numeric_features_fv = FeatureView(
    name="numeric_features",
    entities=[record],
    ttl=timedelta(days=1),
    schema=[
        Field(name="f0",  dtype=Float32),
        Field(name="f1",  dtype=Float32),
        Field(name="f2",  dtype=Float32),
        Field(name="f3",  dtype=Float32),
        Field(name="f4",  dtype=Float32),
        Field(name="f5",  dtype=Float32),
        Field(name="f6",  dtype=Float32),
        Field(name="f7",  dtype=Float32),
        Field(name="f8",  dtype=Float32),
        Field(name="f9",  dtype=Float32),
        Field(name="f10", dtype=Float32),
        Field(name="f11", dtype=Float32),
        Field(name="f12", dtype=Float32),
        Field(name="f13", dtype=Float32),
        Field(name="f14", dtype=Float32),
        Field(name="f15", dtype=Float32),
        Field(name="f16", dtype=Float32),
        Field(name="f17", dtype=Float32),
        Field(name="f18", dtype=Float32),
        Field(name="f19", dtype=Float32),
    ],
    source=numeric_source,
    tags={"team": "mlops", "domain": "generic", "version": "v2"},
    online=True,    # Materialized to Redis
)

# Entity metadata — categorical and string columns with longer TTL
entity_metadata_fv = FeatureView(
    name="entity_metadata",
    entities=[record],
    ttl=timedelta(days=7),
    schema=[
        Field(name="category",         dtype=String),
        Field(name="source",           dtype=String),
        Field(name="row_count",        dtype=Int64),
        Field(name="label",            dtype=Int64),    # classification target
        Field(name="split",            dtype=String),   # train | val | test
        Field(name="dataset_version",  dtype=String),   # matches schema_registry.version
        Field(name="workflow_id",      dtype=String),   # lineage back-reference
    ],
    source=metadata_source,
    tags={"team": "mlops", "domain": "metadata", "version": "v2"},
    online=True,
)


# Training feature retrieval (used by TrainingAgent in Phase 2) 
def get_training_features(
    store: FeatureStore,
    entity_df: pd.DataFrame,
    feature_refs: Optional[list[str]] = None,
) -> pd.DataFrame:
    if feature_refs is None:
        feature_refs = [
            f"numeric_features:{f.name}"
            for f in numeric_features_fv.schema
        ] + [
            "entity_metadata:category",
            "entity_metadata:label",
        ]

    logger.info(
        "Retrieving %d historical features for %d entities",
        len(feature_refs), len(entity_df),
    )
    return store.get_historical_features(
        entity_df=entity_df,
        features=feature_refs,
    ).to_df()


def get_online_features(
    store: FeatureStore,
    record_ids: list[int],
    feature_refs: Optional[list[str]] = None,
) -> pd.DataFrame:
    if feature_refs is None:
        feature_refs = [
            f"numeric_features:{f.name}"
            for f in numeric_features_fv.schema
        ]

    entity_rows = [{"record_id": rid} for rid in record_ids]
    response = store.get_online_features(
        features=feature_refs,
        entity_rows=entity_rows,
    ).to_dict()

    return pd.DataFrame(response)


# Dynamic feature view registration
def register_dynamic_feature_view(
    store: FeatureStore,
    dataset_id: str,
    df: pd.DataFrame,
    source_path: str,
    ttl_days: int = 1,
) -> FeatureView:
    """
    Register a FeatureView whose schema is derived from the REAL ingested
    dataframe's own columns/dtypes, backed by the REAL per-workflow Parquet
    file DataAgent just wrote (source_path) — not the synthetic dev fixture.

    Called by DataAgent._materialize_features() on every ingestion so Feast
    actually serves what was ingested, instead of only ever serving
    generate_dev_fixture()'s synthetic f0..f19 columns.
    """
    from feast.types import Float32, Float64, Int64, String

    _pandas_to_feast = {
        "float32": Float32,
        "float64": Float64,
        "int32":   Int64,
        "int64":   Int64,
        "object":  String,
        "string":  String,
        "bool":    Int64,     # Feast does not have a native Bool type in all versions
    }

    # Build fields from DataFrame dtypes, skip Feast metadata columns
    _feast_reserved = {"record_id", "event_timestamp", "created_timestamp"}
    fields = []
    for col in df.columns:
        if col in _feast_reserved:
            continue
        dtype_str = str(df[col].dtype)
        feast_type = _pandas_to_feast.get(dtype_str, String)
        fields.append(Field(name=col, dtype=feast_type))

    if not fields:
        logger.warning(
            "register_dynamic_feature_view: no non-reserved columns found in df for %s",
            dataset_id,
        )
        return numeric_features_fv   # fallback to static view

    source = FileSource(
        path=source_path,
        timestamp_field="event_timestamp",
    )

    fv = FeatureView(
        name=f"{dataset_id}_features",
        entities=[record],
        ttl=timedelta(days=ttl_days),
        schema=fields,
        source=source,
        tags={"team": "mlops", "dataset_id": dataset_id, "auto_generated": "true"},
        online=True,
    )

    # Apply the new view to the store
    store.apply([record, fv])
    logger.info(
        "Dynamic FeatureView registered: name=%s fields=%d ttl_days=%d source=%s",
        fv.name, len(fields), ttl_days, source_path,
    )
    return fv

def generate_dev_fixture(
    output_path: Optional[str] = None,
    n_rows: int = 2000,
    n_numeric_features: int = 20,
) -> str:
    """
    Write a development fixture parquet with schema matching the static feature views.

    In production the DataAgent writes real ingested data here.
    This fixture exists only so engineers can run `feast apply` locally
    without needing real R2 credentials.

    Returns the path written.
    """
    import numpy as np
    from datetime import datetime, timezone

    output_path = output_path or str(_OFFLINE_DATA_DIR / "features_dev_fixture.parquet")
    Path(output_path).parent.mkdir(parents=True, exist_ok=True)

    rng = np.random.default_rng(seed=42)
    data: dict = {}
    for i in range(n_numeric_features):
        data[f"f{i}"] = rng.standard_normal(n_rows).astype("float32")

    data["record_id"]       = list(range(n_rows))
    data["label"]           = rng.integers(0, 2, size=n_rows).tolist()
    data["category"]        = rng.choice(["A", "B", "C"], size=n_rows).tolist()
    data["source"]          = ["dev_fixture"] * n_rows
    data["row_count"]       = [n_rows] * n_rows
    data["split"]           = rng.choice(["train", "val"], p=[0.8, 0.2], size=n_rows).tolist()
    data["dataset_version"] = ["1.0.0"] * n_rows
    data["workflow_id"]     = ["dev_fixture"] * n_rows
    data["event_timestamp"] = [datetime.now(timezone.utc)] * n_rows

    df = pd.DataFrame(data)
    df.to_parquet(output_path, index=False)
    logger.info("Dev fixture written: path=%s rows=%d", output_path, n_rows)
    print(f"✅ Dev fixture written: {output_path} ({n_rows} rows)")
    return output_path


if __name__ == "__main__":
    generate_dev_fixture()